services:
  - type: static
    name: coach-fit-client
    buildCommand: cd client-app && npm install && npm run build
    staticPublishPath: ./client-app/dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_URL
        value: http://103.88.243.123:8000

