services:
  - type: static
    name: coach-flo-client
    buildCommand: cd client-app && npm install && npm run build
    staticPublishPath: ./client-app/dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_URL
        value: "/"
    routes:
      - type: rewrite
        source: /api/*
        destination: http://103.88.243.123/api/*
      - type: rewrite
        source: /*
        destination: /index.html

